// Generated by CoffeeScript 1.11.1
(function() {
  var app, bodyParser, d3, express, fs, http, metrics, path, url, user;

  http = require('http');

  user = require('./user.coffee');

  metrics = require('./metrics.coffee');

  url = require('url');

  fs = require('fs');

  express = require('express');

  bodyParser = require('body-parser');

  app = express();

  d3 = require('d3');

  path = require('path');

  app.set('port', 1337);

  app.set('views', __dirname + "/../views");

  app.set('view engine', 'jade');

  app.use('/public', express["static"](__dirname + "/../public"));

  app.use('/styles', express["static"](__dirname + "/../styles"));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded());

  app.listen(app.get('port'), function() {
    return console.log("server listening on " + (app.get('port')));
  });

  app.get('/', function(req, res) {
    return res.render('index', {});
  });

  app.get('/hello/:name', function(req, res) {
    return res.send("Hello " + req.params.name);
  });

  app.get('/metrics.json', function(req, res) {
    return metrics.get(function(err, data) {
      if (err) {
        throw next(err);
      }
      res.status(200).json(data);
      return console.log("got param :");
    });
  });

  app.get('/metrics', function(req, res) {
    metrics.InitChart();
    return res.sendFile(path.resolve('views/metrics.html'));
  });

  app.post('/metrics', function(req, res) {
    var color, name;
    name = req.body.timestamp;
    color = req.body.value;
    console.log("param !!" + name + color);
    return metrics.save(0, req.body, function(err) {
      if (err) {
        throw err;
      }
    });
  });

  app.put('/', function(req, res) {});

  app["delete"]('/', function(req, res) {});

}).call(this);
