// Generated by CoffeeScript 1.11.1
(function() {
  var app, express, fs, http, url, user;

  http = require('http');

  user = require('./user.coffee');

  url = require('url');

  fs = require('fs');

  express = require('express');

  app = express();

  app.set('port', 1337);

  app.listen(1337, function() {
    return console.log("server listening on 1337");
  });

  a;

}).call(this);
